### ISSUE TITLE
How to restore apps into a new environment.

### ISSUE THREAD

**Issue by YasutoshiT** [akamai/cli-eaa#5]
Hello

I want to know if there are any ways to restore apps into a new eaa environment.

Actually I'm in the middle of PoC, the environment has more than 30 apps.
I could export these 30 apps into each separated json files.

And new live environment will be ready next month. So I want to know how to restore these 30 apps into a new environment using cli-eaa. Is this possible?

Thanks in advance.

**Comment by bitonio** [comment]
Hi,

The backup function will store all the information contained in the EAA application configuration.

The restore function is not able to restore 100% of it for now.
One reason is each configuration has some dependencies like IdP or Connector UUID, these will change in a new (different) environment. That's why we started to use some JINJA template logic you can use aliases and let the cli deals with the real UUID. I provided [some examples](https://github.com/akamai/cli-eaa/releases/tag/0.2.6) that may help you get started.

I'd consider the restore (also "create from JSON") support as _partial_ because not everything is tested/implemented/supported, among:
- application icon/image
- application category
- MFA settings
- ICAP config
- OIDC app facing auth

If your applications are not using any of these, you might give it a shot, I can help you off-thread (firstname dot lastname at akamai dot com).
